/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calculadora.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
rpc_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		flotantes suma_1_arg;
		flotantes resta_1_arg;
		flotantes multiplica_1_arg;
		flotantes divide_1_arg;
		flotantes_trigonometricas seno_1_arg;
		flotantes_trigonometricas coseno_1_arg;
		flotantes_trigonometricas tangente_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case suma:
		_xdr_argument = (xdrproc_t) xdr_flotantes;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) suma_1_svc;
		break;

	case resta:
		_xdr_argument = (xdrproc_t) xdr_flotantes;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) resta_1_svc;
		break;

	case multiplica:
		_xdr_argument = (xdrproc_t) xdr_flotantes;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) multiplica_1_svc;
		break;

	case divide:
		_xdr_argument = (xdrproc_t) xdr_flotantes;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) divide_1_svc;
		break;

	case seno:
		_xdr_argument = (xdrproc_t) xdr_flotantes_trigonometricas;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) seno_1_svc;
		break;

	case coseno:
		_xdr_argument = (xdrproc_t) xdr_flotantes_trigonometricas;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) coseno_1_svc;
		break;

	case tangente:
		_xdr_argument = (xdrproc_t) xdr_flotantes_trigonometricas;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) tangente_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (rpc, rpcprueba);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, rpc, rpcprueba, rpc_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (rpc, rpcprueba, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, rpc, rpcprueba, rpc_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (rpc, rpcprueba, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
