/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULADORA_H_RPCGEN
#define _CALCULADORA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct flotantes {
	float a;
	float b;
};
typedef struct flotantes flotantes;

struct flotantes_trigonometricas {
	float a;
};
typedef struct flotantes_trigonometricas flotantes_trigonometricas;

#define rpc 0xffff
#define rpcprueba 1

#if defined(__STDC__) || defined(__cplusplus)
#define suma 1
extern  float * suma_1(flotantes *, CLIENT *);
extern  float * suma_1_svc(flotantes *, struct svc_req *);
#define resta 2
extern  float * resta_1(flotantes *, CLIENT *);
extern  float * resta_1_svc(flotantes *, struct svc_req *);
#define multiplica 3
extern  float * multiplica_1(flotantes *, CLIENT *);
extern  float * multiplica_1_svc(flotantes *, struct svc_req *);
#define divide 4
extern  float * divide_1(flotantes *, CLIENT *);
extern  float * divide_1_svc(flotantes *, struct svc_req *);
#define seno 5
extern  float * seno_1(flotantes_trigonometricas *, CLIENT *);
extern  float * seno_1_svc(flotantes_trigonometricas *, struct svc_req *);
#define coseno 6
extern  float * coseno_1(flotantes_trigonometricas *, CLIENT *);
extern  float * coseno_1_svc(flotantes_trigonometricas *, struct svc_req *);
#define tangente 7
extern  float * tangente_1(flotantes_trigonometricas *, CLIENT *);
extern  float * tangente_1_svc(flotantes_trigonometricas *, struct svc_req *);
extern int rpc_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define suma 1
extern  float * suma_1();
extern  float * suma_1_svc();
#define resta 2
extern  float * resta_1();
extern  float * resta_1_svc();
#define multiplica 3
extern  float * multiplica_1();
extern  float * multiplica_1_svc();
#define divide 4
extern  float * divide_1();
extern  float * divide_1_svc();
#define seno 5
extern  float * seno_1();
extern  float * seno_1_svc();
#define coseno 6
extern  float * coseno_1();
extern  float * coseno_1_svc();
#define tangente 7
extern  float * tangente_1();
extern  float * tangente_1_svc();
extern int rpc_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_flotantes (XDR *, flotantes*);
extern  bool_t xdr_flotantes_trigonometricas (XDR *, flotantes_trigonometricas*);

#else /* K&R C */
extern bool_t xdr_flotantes ();
extern bool_t xdr_flotantes_trigonometricas ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULADORA_H_RPCGEN */
